services:
  postgres:
    container_name: postgres
    image: postgres:17.5-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: skibidi
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 54321:54321
